import { ManUnited, ManCity,RightArrowWh, LeftArrowWh, DownArrowWh, } from "../assets";
//--------------------------------------------------------------------------
 const navItems = [
  "Football",
  "Tennis",
  "Basketball",
  "Hockey",
  "Hand ball",
  "Cricket",
  "Volleyball",
  "Table Tennis",
];

export const Card1 = [
  {
    leagueName: "Premier League",
    leagueLogo: "../assets/PLlogo.png",
    countryName: "England",
    flagIcon: "../assets/PLlogo.png",
    totalMatches: 380,
    totalGoals: 1032,
    totalFoulCards: 653,
  },
];

export const folderPath = [
  { name: "England", link: "/folder1" },
  { name: "Premier League", link: "/folder2" },
];

//--------------------------------------------------------------------------
export const navLinks = [
  {
    id: "football",
    title: "Football",
  },
  {
    id: "tennis",
    title: "Tennis",
  },
  {
    id: "basketball",
    title: "Basketball",
  },
  {
    id: "hockey",
    title: "Hockey",
  },
  {
    id: "cricket",
    title: "Cricket",
  },
  {
    id: "volleyball",
    title: "Volleyball",
  },
  {
    id: "table-tennis",
    title: "Table Tennis",
  },
];

export const years = [
  "2019-2020",
  "2020-2021",
  "2021-2022",
  "2022-2023",
  "2019-2020",
  "2020-2021",
  "2021-2022",
  "2022-2023", // Add more years as needed
];


export const standingsData = [
  {
    rank: 1,
    img: ManCity,
    team: "Manchester City",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 1,
    img: ManCity,
    team: "Manchester City",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 1,
    img: ManCity,
    team: "Manchester City",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },{
    rank: 1,
    img: ManCity,
    team: "Manchester City",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },{
    rank: 1,
    img: ManCity,
    team: "Manchester City",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
  {
    rank: 2,
    img: ManUnited,
    team: "Manchester united",
    played: 21,
    won: 21,
    drawn: 21,
    lost: 21,
    goals: 21,
    points: 62,
  },
];

export const matches =  [
  {
  Date: "14-12-2022",
  Matches:[
    {
      MatchID: 144,
      homeTeam: 'Mancity',
      awayTeam: 'ManUtd',
      homeScore: 3,
      awayScore: 1,
      homeLogoSrc: ManCity,
      awayLogoSrc: ManUnited,
    },
    {
      MatchID: 155,
      homeTeam: 'Mancity',
      awayTeam: 'ManUtd',
      homeScore: 5,
      awayScore: 3,
      homeLogoSrc: ManCity,
      awayLogoSrc: ManUnited,
      },
  ],
  },
    {
      Date : "15-12-2022",
      Matches:[
          {
            MatchID: 111,
            homeTeam: 'Mancity',
            awayTeam: 'ManUtd',
            homeScore: 5,
            awayScore: 3,
            homeLogoSrc: ManCity,
            awayLogoSrc: ManUnited,
          },
          {
            MatchID: 122,
          homeTeam: 'Mancity',
          awayTeam: 'ManUtd',
          homeScore: 3,
          awayScore: 1,
          homeLogoSrc: ManCity,
          awayLogoSrc: ManUnited,
          },
          {
            MatchID: 133,
            homeTeam: 'Mancity',
            awayTeam: 'ManUtd',
            homeScore: 5,
            awayScore: 3,
            homeLogoSrc: ManCity,
            awayLogoSrc: ManUnited,
          },
      ],
    },
    {
      Date : "16-12-2022",
      Matches:[
        {
          MatchID: 110,
          homeTeam: 'Mancity',
          awayTeam: 'ManUtd',
          homeScore: 3,
          awayScore: 1,
          homeLogoSrc: ManCity,
          awayLogoSrc: ManUnited,
        },
        {
          MatchID: 120,
          homeTeam: 'Mancity',
          awayTeam: 'ManUtd',
          homeScore: 5,
          awayScore: 3,
          homeLogoSrc: ManCity,
          awayLogoSrc: ManUnited,
          },
      ],
    },
  ];